---
- hosts: all
  gather_facts: yes
  become: True

- hosts: web_node
  roles:
    - cmndrsp0ck.ansible-nginx-backend
  become: True

- hosts: load_balancer
  roles:
    - cmndrsp0ck.ansible-haproxy-tls-termination
  become: True
